language: java

sudo: false

before_script:
  - cd JHazm
  - mkdir -p src/test/resources/resources
  - cp -avr resources src/test/resources/
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 46f3b59e-ab1c-4aa9-aa83-c5b1f41ea647

jdk:
  - oraclejdk8
